#ESP_ROOT=C:/msys64/usr/Arduino/hardware/espressif/esp32
ESP_ROOT=$(HOME)/usr/Arduino/hardware/espressif/esp32
CHIP=esp32

# Comment out for using files in current directory
#SKETCH = $(ESP_ROOT)/libraries/Ticker/examples/TickerBasic/TickerBasic.ino

#UPLOAD_PORT = /dev/COM4
#UPLOAD_PORT = /dev/tty.SLAB_USBtoUART #MACOSX
UPLOAD_PORT = /dev/ttyUSB0	#Ubuntu
UPLOAD_SPEED=921600
#BOARD = esp32

#include C:/msys64/home/arduino/work/Arduino/makeEspArduino/makeEspArduino.mk
include $(HOME)/usr/Arduino/makeEspArduino/makeEspArduino.mk

